### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by CharesFang** [hzysvilla/Academic_Smart_Contract_Papers#1]
Hi, is there any contribution guide? I'm working on studying the security topics related to smart contract recently. I have collected some other papers about smart contract, there may be 3 or 4 not included in this repo. Can I just create a PR?

**Comment by hzysvilla** [comment]
There is no requirement, just submit the PR.  More contributions to the field of contract security are welcome.

**Comment by CharesFang** [comment]
> There is no requirement, just submit the PR. More contributions to the field of contract security are welcome.

Thanks a lot. I will attach my collected paper in the later PR.
