### ISSUE TITLE
Including SEFM Conference papers

### ISSUE THREAD

**Issue by mojtaba-eshghie** [hzysvilla/Academic_Smart_Contract_Papers#14]
To my understanding there are two papers presented on smart contract verification on this year's SEFM. The second is my paper.

SSCalc - A Calculus for Solidity Smart Contracts
Diego Marmsoler and Billy Thornton

Capturing Smart Contract Design with DCR Graphs
Mojtaba Eshghie, Wolfgang Ahrendt, Cyrille Valentin Artho, Thomas Hildebrandt and Gerardo Schneider

Program of  [21st International Conference on Software Engineering and Formal Methods](https://sefm-conference.github.io/2023/program/)

**Comment by mojtaba-eshghie** [comment]
I can fork and add the conference+paper info if you'll merge the pull request.

**Comment by hzysvilla** [comment]
Contributions are welcome, please submit your PR.
