### ISSUE TITLE
Inquiry about CCS23 demystifying defi mev activities in flashbots bundle

### ISSUE THREAD

**Issue by hyue0768** [hzysvilla/Academic_Smart_Contract_Papers#15]
I cant find any files related to this paper "demystifying defi mev activities in flashbots bundle", can you share me any information about how to download it? Thanks

**Comment by hzysvilla** [comment]
The author decided to wait to make his paper available until it becomes publicly available, but you can see a detailed description of the research in the article (https://mp.weixin.qq.com/s/-LuyZAi0zf-TPomaW39qTw).
